language: java

# Use container based builds. They are faster and we do not need sudo.
sudo: false

jdk:
  - openjdk8
  - oraclejdk8
  
dist: trusty

script: 
 - mvn -P packaging-jar clean install   

branches:
  only:
  - master
  